# Regenerates apps/web/src/data/dummyNames.ts.
#   • Supplied states: randomly sampled from StateWiseExcels/*.xlsx.
#   • Uttar Pradesh: retain the existing pool (no supplied workbook).
# Run: python packages/trpc/scripts/gen-dummy-names.py
import openpyxl, random, json, collections, os
from pathlib import Path

random.seed(42)  # reproducible sampling
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "../../.."))
SOURCE_DIR = Path(ROOT) / "StateWiseExcels"
OUT = os.path.join(ROOT, "apps", "web", "src", "data", "dummyNames.ts")

NAMES_PER_STATE = 90

# ── Name-only samples from the supplied regional workbooks ────────────────
def sample_workbooks():
    by_state = collections.defaultdict(list)
    paths = sorted(SOURCE_DIR.glob("*.xlsx"))
    if not paths:
        raise ValueError(f"No workbooks found in {SOURCE_DIR}")
    for path in paths:
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        try:
            for ws in wb:
                rows = ws.iter_rows(values_only=True)
                for row in rows:
                    if "Full Name" in row and "Gender" in row and "State" in row:
                        name_idx = row.index("Full Name")
                        gender_idx = row.index("Gender")
                        state_idx = row.index("State")
                        break
                else:
                    raise ValueError(f"Missing name headers: {path.name}/{ws.title}")
                for row in rows:
                    if not any(value is not None for value in row):
                        continue
                    name, gender, state = row[name_idx], row[gender_idx], row[state_idx]
                    gender = str(gender).strip().lower()
                    if not name or not state or gender not in ("male", "female"):
                        raise ValueError(f"Invalid name record: {path.name}/{ws.title}")
                    by_state[str(state).strip()].append({"n": str(name).strip(), "g": gender[0]})
        finally:
            wb.close()
    out = {}
    sampler = random.Random(42)
    for state, names in by_state.items():
        # Shuffle before sampling; never alphabetize names.
        seen, uniq = set(), []
        sampler.shuffle(names)
        for x in names:
            if x["n"] in seen:
                continue
            seen.add(x["n"]); uniq.append(x)
        out[state] = uniq[:NAMES_PER_STATE]
    return out

# Preserved Uttar Pradesh pool for Noida/Lucknow (no workbook supplied).
UP_NAMES = [
  {
    "n": "Nitin Shukla",
    "g": "m"
  },
  {
    "n": "Neha Pandey",
    "g": "f"
  },
  {
    "n": "Shweta Nigam",
    "g": "f"
  },
  {
    "n": "Ruchi Gaur",
    "g": "f"
  },
  {
    "n": "Priyanka Shukla",
    "g": "f"
  },
  {
    "n": "Saurabh Rastogi",
    "g": "m"
  },
  {
    "n": "Prashant Gaur",
    "g": "m"
  },
  {
    "n": "Rajeev Mishra",
    "g": "m"
  },
  {
    "n": "Anurag Saxena",
    "g": "m"
  },
  {
    "n": "Richa Shukla",
    "g": "f"
  },
  {
    "n": "Devesh Singh",
    "g": "m"
  },
  {
    "n": "Swati Bajpai",
    "g": "f"
  },
  {
    "n": "Pooja Chaturvedi",
    "g": "f"
  },
  {
    "n": "Akhilesh Dubey",
    "g": "m"
  },
  {
    "n": "Vaibhav Awasthi",
    "g": "m"
  },
  {
    "n": "Abhishek Verma",
    "g": "m"
  },
  {
    "n": "Ankur Gaur",
    "g": "m"
  },
  {
    "n": "Astha Dubey",
    "g": "f"
  },
  {
    "n": "Manish Pathak",
    "g": "m"
  },
  {
    "n": "Aarti Nigam",
    "g": "f"
  },
  {
    "n": "Anamika Awasthi",
    "g": "f"
  },
  {
    "n": "Gaurav Singh",
    "g": "m"
  },
  {
    "n": "Ankita Gaur",
    "g": "f"
  },
  {
    "n": "Aditya Srivastava",
    "g": "m"
  },
  {
    "n": "Praveen Chaturvedi",
    "g": "m"
  },
  {
    "n": "Preeti Tripathi",
    "g": "f"
  },
  {
    "n": "Vandana Bajpai",
    "g": "f"
  },
  {
    "n": "Shalini Mishra",
    "g": "f"
  },
  {
    "n": "Himanshu Upadhyay",
    "g": "m"
  },
  {
    "n": "Madhuri Chaturvedi",
    "g": "f"
  },
  {
    "n": "Vineet Yadav",
    "g": "m"
  },
  {
    "n": "Shivam Yadav",
    "g": "m"
  },
  {
    "n": "Deepti Gaur",
    "g": "f"
  },
  {
    "n": "Garima Shukla",
    "g": "f"
  },
  {
    "n": "Vivek Awasthi",
    "g": "m"
  },
  {
    "n": "Utkarsh Yadav",
    "g": "m"
  },
  {
    "n": "Nidhi Verma",
    "g": "f"
  },
  {
    "n": "Sneha Tripathi",
    "g": "f"
  },
  {
    "n": "Ashutosh Verma",
    "g": "m"
  },
  {
    "n": "Kanchan Saxena",
    "g": "f"
  }
]

supplied = sample_workbooks()
by_state = {**supplied, "Uttar Pradesh": UP_NAMES}

# DEFAULT fallback pool for any state not listed: a pan-India blend.
default = []
for st in ["Delhi", "Maharashtra", "West Bengal", "Karnataka", "Gujarat"]:
    default += by_state.get(st, [])[:12]
random.shuffle(default)

def dump(arr):
    return "[\n" + ",\n".join(f'  {{ "n": {json.dumps(x["n"])}, "g": "{x["g"]}" }}' for x in arr) + ",\n]"

lines = []
lines.append("// Auto-generated by packages/trpc/scripts/gen-dummy-names.py — do not hand-edit.")
lines.append("// Sample names randomly selected from StateWiseExcels, grouped by state.")
lines.append("// Uttar Pradesh retains its previous pool; no workbook was supplied.")
lines.append("// Names are sample data, not evidence of actual buyer activity.")
lines.append('export type DummyName = { n: string; g: "m" | "f" };')
lines.append("")
lines.append("export const NAMES_BY_STATE: Record<string, DummyName[]> = {")
for state in sorted(by_state):
    body = ",\n".join(f'    {{ n: {json.dumps(x["n"])}, g: "{x["g"]}" }}' for x in by_state[state])
    lines.append(f"  {json.dumps(state)}: [\n{body},\n  ],")
lines.append("};")
lines.append("")
body = ",\n".join(f'  {{ n: {json.dumps(x["n"])}, g: "{x["g"]}" }}' for x in default)
lines.append(f"export const DEFAULT_NAMES: DummyName[] = [\n{body},\n];")
lines.append("")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Wrote", OUT)
for s in sorted(by_state):
    print(f"  {s}: {len(by_state[s])}")
print("DEFAULT:", len(default))
